"""empty message

Revision ID: 3ed5ee0c6636
Revises: b5e697796813
Create Date: 2023-08-22 00:14:19.046344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed5ee0c6636'
down_revision = 'b5e697796813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.String(length=30),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
